### ISSUE TITLE
Can't make it work..

### ISSUE THREAD

**Issue by planetcrypton** [atugushev/django-password-session#3]
Hi,

I've adjusted my settings and implemented the flow into my project, and testing it over two browsers, but can't seem to get it working.

Here's my code from my view.
The form's EditProfileForm.save() method sets `self.user.set_password( data['password1'] )` (called in my shortcut-function `validate_n_save(request,form)`).
Back in the view I call `update_session_auth_hash(request, inst.user)`.

``` python
        form = EditProfileForm(request.user, request.POST, request.FILES, instance=profile)
        inst = validate_n_save(request,form)
        if form.cleaned_data.get('password_changed', False):
            # invalidate all active sessions after change password
            # check by print if get here..
            print 'update_session_auth_hash'
            update_session_auth_hash(request, inst.user)
```

I've got two browsers open, both with the same user logged in.

When one browser changes the user's password, the other browser's user remains logged in, where I expected that user to be logged out.

**Comment by atugushev** [comment]
Hi!

Thank you for the report. Could you tell me about your Django version?

**Comment by planetcrypton** [comment]
Sorry I didn't mention that: Django version 1.6.5

**Comment by atugushev** [comment]
Make sure that `self.user.save()` called inside `EditProfileForm.save()`.  It seems a signal `post_save` of the User model is not sent.

Otherwise, i have no idea what's wrong with your code. It would be nice if you sent me a pull-request with TestCase, which causes this bug.

Thanks.

**Comment by planetcrypton** [comment]
I'm so sorry, my bad!! : I'd overlooked middleware
'password_session.middleware.CheckPasswordHash' to be added...
Works like a charm :)

On Tue, Jun 23, 2015 at 3:20 PM, Albert Tugushev notifications@github.com
wrote:

> Make sure that self.user.save() called inside
> validate_n_save(request,form). It seems a signal post_save of the User
> model is not sent.
> 
> Otherwise, i have no idea what's wrong with your code. It would be nice if
> you sent me a pull-request with TestCase, which causes this bug.
> 
> Thanks.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/atugushev/django-password-session/issues/3#issuecomment-114497948
> .

## 

Mvh Sjoerd Kok

**Comment by planetcrypton** [comment]
Closing this issue :)
